### ISSUE TITLE
Install success but has errors

### ISSUE THREAD

**Issue by majimboo** [thumbor/opencv-engine#1]
Went ahead to try, I am using amazon ec2 ubuntu 13.10. I have the same version at home and it works. But now this is the error.

    Downloading/unpacking opencv-engine
      Downloading opencv_engine-0.1.0.tar.gz
      Running setup.py egg_info for package opencv-engine
        libdc1394 error: Failed to initialize libdc1394
    
    Requirement already satisfied (use --upgrade to upgrade): thumbor in /usr/local/lib/python2.7/dist-packages/thumbor-4.0.0-py2.7-linux-x86_64.egg (from opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): tornado>=2.1.1,<3.2.0 in /usr/local/lib/python2.7/dist-packages (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): pyCrypto>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): pycurl>=7.19.0,<7.20.0 in /usr/lib/python2.7/dist-packages (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.1.0,<2.4.0 in /usr/local/lib/python2.7/dist-packages (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): derpconf>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): python-magic>=0.4.3 in /usr/local/lib/python2.7/dist-packages (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): pexif==0.13 in /usr/local/lib/python2.7/dist-packages/pexif-0.13-py2.7.egg (from thumbor->opencv-engine)
    Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from derpconf>=0.2.0->thumbor->opencv-engine)
    Installing collected packages: opencv-engine
      Running setup.py install for opencv-engine
        libdc1394 error: Failed to initialize libdc1394
    
    Successfully installed opencv-engine
    Cleaning up...

**Comment by scorphus** [comment]
ping, @majimboo

**Comment by scorphus** [comment]
This is an OpenCV issue. [TravisCI build](https://travis-ci.org/thumbor/opencv-engine#L384) also shows this message. I'm closing this one.
