### ISSUE TITLE
Support for OpenCV 3.0?

### ISSUE THREAD

**Issue by Bladrak** [thumbor/opencv-engine#15]
Hello,

OpenCV 3.0 being out and relatively stable, is opencv-engine compatible with this version?

I've tried it on a VM, but ran into some errors. One of them was the import, that I fixed with the following code:

```
try:
    import cv
except ImportError:
    import cv2.cv as cv
except ImportError:
    import cv2 as cv
```

But when trying to request an image, I now get the following:

```
2015-08-12 10:02:39 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 97, in get_image
    engine.load(buffer, self.context.request.extension)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 96, in load
    image_or_frames = self.create_image(buffer)
  File "/usr/local/lib/python2.7/dist-packages/opencv_engine/engine.py", line 78, in create_image
    imagefiledata = cv.CreateMatHeader(1, len(buffer), cv.CV_8UC1)
AttributeError: 'module' object has no attribute 'CreateMatHeader'
```

I'm guessing the engine is not compatible with OpenCV 3.0 at the moment, but is there any plan to make it so? Do you need help in this?

I'm using opencv-engine 1.0.1.

Thanks for any information!

**Comment by heynemann** [comment]
I don't think it is. We would need to find the functions we use in the engine and remap them to the proper opencv implementation. Maybe it's best to isolate all the calls to openCV in an implementation module within this engine (opencv2.py, opencv3.py) and both have the same methods that the engine calls. They just implement them differently.

**Comment by Bladrak** [comment]
Thanks for the answer @heynemann :)

I was actually trying to enable webP format support, but it seems it's only available in OpenCV >= 3 :/

I'll try to work on that implementation then if that's ok with you, I'll begin by adding an ``engine_cv3.py`` file to ensure BC by not renaming the current engine file. Does that seem right?

**Comment by heynemann** [comment]
It does. If we can support both I'm all for it.

**Comment by Bladrak** [comment]
Cool. I'll try to work on that whenever I get the time then :)

**Comment by gmarchand** [comment]
:+1:

**Comment by samuelmichaud** [comment]
:+1:

**Comment by eranhazout** [comment]
Hi
Any progress with that? we are also trying to use OpenCV3 with webp support on thumbor.

**Comment by bagipriyank** [comment]
any progress on this? we would like to use webp support on thumbor with opencv engine.

**Comment by christianjgreen** [comment]
opencv3 support has been added
